---
#
# The hosts group used is provided by the group variable or defaulted to 'Intersight_Servers'.
# You can specify a specific host (or host group) on the command line:
#   ansible-playbook ... -e group=<your host group>
#   e.g., ansible-playbook server_profiles.yml -e group=TME_Demo
#
- hosts: "{{ group | default('Intersight_HX') }}"
  connection: local
  gather_facts: false
  vars:
    # Create an anchor for api_info that can be used throughout the file
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  
  tasks:
    # Claim device
    - name: Debug device claim
      debug:
        msg: " Server serial: {{ item[0] }} and Code: {{ item[1] }}"
      loop: "{{ toClaimHostList }}"
      when: debug == True
      
    - name: Claim device
      cisco.intersight.intersight_rest_api:
        <<: *api_info
        resource_path: /asset/DeviceClaims
        api_body: {
          "SecurityToken": "{{ item[1] }}",
          "SerialNumber": "{{ item[0] }}"
        }
        update_method: post
      loop: "{{ toClaimHostList }}"
      # delegate_to: localhost
      # run_once: true
